# Generated by Django 6.0.4 on 2026-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_subscriptionplan_transaction_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
