# Generated by Django 6.0.4 on 2026-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='maps_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
