# Generated by Django 6.0.4 on 2026-04-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
